### ISSUE TITLE
Feature request - Sticky notifications

### ISSUE THREAD

**Issue by skamsie** [reportaman/arttime#11]
Hi, first of all great app! Is there a way to configure the notifications to be sticky on Mac OS? Currently it shows up for a second or so, then it dissapears. I would like to have the type of notifications that you have to manually close.

**Comment by reportaman** [comment]
@skamsie Am glad you find like it. Yes there is a way! Its already listed in the [https://github.com/reportaman/arttime#troubleshooting](https://github.com/reportaman/arttime#troubleshooting) section of arttime's [README.md](https://github.com/reportaman/arttime#readme). Am copying it here for your reference:

- Notifications for arttime do not stay for long time on macOS?
  - This setting cannot be controlled by arttime. You will have to do this 1 time change in your computer: Open System Preferences > Select Notifications & Focus > Scroll to Script Editor > Change "Script editor alert style" to "Alerts". Make sure "Allow Notifications" is selected. Additionally check the combination of boxes based on your preferences.

This will change behavior notifications generated of all apple scripts that you write. It seems like there is no native macOS interface like Linux to change this behavior on per notification basis. This 1 time change should not affect the behavior of notifications from other apps. Screenshot below shows how I have configured AppleScript notifications.

<img width="665" alt="Screen Shot 2022-06-26 at 9 35 17 AM" src="https://user-images.githubusercontent.com/71736629/175824671-5f2a5e7b-e5fd-45de-963a-b35cd93ae727.png">

**Comment by skamsie** [comment]
Solved, thank you!

**Comment by reportaman** [comment]
A related setting needs change if notifications do not always appear (due to focus settings). I just added this bullet to the [Troubleshooting](https://github.com/reportaman/arttime#troubleshooting) section of documentation.

- Notification don't always appear on macOS, example: during a Zoom call?
  - If notifications sometime appear and sometime do not, this is because of macOS "Focus"/"Do not disturb" settings. You will have to do this one time change on your computer: Open System Preferences > Select Notifications & Focus > Select Focus tab > Choose profile "Do not disturb" > In "Allowed notifications from" box select "Apps" tab then press + (i.e. plus) > Search and select "Script Editor" > Press Add. You might have to repeat this process for all focus profiles you use in addition to "Do not disturb".
