### ISSUE TITLE
can't get it to run

### ISSUE THREAD

**Issue by djsnipa1** [reportaman/arttime#9]
Hello,

This project looks amazing and I really would love to use it! Any help would be greatly appreciated! Thank you!

I run the command `arttime` and it is correctly in my `PATH`. Here is the error:
```bash
github/arttime/bin/arttime:zparseopts:18: no default array defined: -F
```

**Comment by reportaman** [comment]
@djsnipa1 This sounds like a zsh version issue. What does your ``zsh --version`` say? Can you try upgrading your zsh to a more newer version (latest is 5.9, but you might not need that) Flag ``-F`` has been supported at least since start of 2020. My systems have zsh 5.8 and above, and arttime works well.

**Comment by reportaman** [comment]
@djsnipa1 Any update?

**Comment by djsnipa1** [comment]
My apologies! I'm checking now...

**Comment by reportaman** [comment]
@djsnipa1 Did you get a chance to upgrade zsh on your system??

**Comment by reportaman** [comment]
Am pretty sure upgrading zsh should resolve this, closing this. In case you encounter a problem after upgrading your zsh, feel free to open another ticket.
